# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rRPZGfNKEG8pap8K30JLWj3R_AmTfy4H
"""

# ROOM 4
# TUGAS MONOPROGRAMING
# 5200411123 - Marhani Wiji Ayu Kusuma
# 5200411143 - Azel Aldi Saputra
# 5200411182 - Nur Rohman Eko Aji
# 5200411186 - Rifqi Helmi Fadhil

print("========= MONOPROGRAMING =========\n")
ram = int(input("Berapa RAM Anda (GB): "))
apk = int(input("Program (GB): "))

# memory os
os = 2048

# Konvert GB to Kbps
gb = 1024

ramk = ram * gb
apkk = apk * gb

# Perhitungan
totalk = os + apkk 
kepake = ramk - (os + apkk)


print("\n============= Hasil ==============\n")
print("Kapasitas RAM = ",ramk,"KBps")
print("Sistem Operasi (OS) = ",os,"KBps")
print("RAM Terpakai = ",totalk,"KBps")
print("RAM Tidak Terpakai = ",kepake,"KBps")